export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_COCKTAIL_ERROR = "ADD_COCKTAIL_ERROR";

export const FETCH_COCKTAILS_ERROR = "FETCH_COCKTAILS_ERROR";
export const FETCH_COCKTAILS_SUCCESS = "FETCH_COCKTAILS_SUCCESS";

export const DELETE_COCKTAIL_ERROR = "DELETE_COCKTAIL_ERROR";
export const PUBLIC_COCKTAIL_ERROR = "PUBLIC_COCKTAIL_ERROR";

export const FETCH_USER_COCKTAILS_ERROR = "FETCH_USER_COCKTAILS_ERROR";
export const FETCH_USER_COCKTAILS_SUCCESS = "FETCH_USER_COCKTAILS_SUCCESS";

export const RATE_COCKTAIL_ERROR = "RATE_COCKTAIL_ERROR";